### ISSUE TITLE
Bold font looks cartoonish recently

### ISSUE THREAD

**Issue by jjw99** [ColorlibHQ/AdminLTE#1527]
Has anyone else noticed that the bold font on the adminlte template has started to look somewhat cartoonish as of about yesterday?
It has happened with my local site that uses adminlte as a base template, and I see the same on the adminlte template at https://adminlte.io/themes/AdminLTE/index2.html

It seems as if something in the Source Sans Pro font might have changed?

**Comment by KolyaNET** [comment]
I, too, yesterday (June 6, 2017) noticed this behavior of fonts.
Can it be updated fonts on Google Fonts?
And who knows the best way to return how it was?

**Comment by yoyo837** [comment]
I use offline google font files and will not become like that.  'So lucky':)

**Comment by jjw99** [comment]
@yoyo837 , any chance you could post those somewhere?

**Comment by REJack** [comment]
That's not a issue from AdminLTE, this can only be caused by Google or your Browser.

@jjw99 You can download from [Adobe's GitHub Repo](https://github.com/adobe-fonts/source-sans-pro/releases) or directly from [Google's Font Site](https://fonts.google.com/specimen/Source+Sans+Pro?selection.family=Source+Sans+Pro)

**Comment by jjw99** [comment]
No one is blaming AdminLTE. I'm just wondering if there is a workaround that can be made for what I suspect was a change in the google font.
