### ISSUE TITLE
jvectormap is not maintened since Aug 2015

### ISSUE THREAD

**Issue by brot** [ColorlibHQ/AdminLTE#1670]
> $ yarn add admin-lte
> yarn add v1.1.0
> info No lockfile found.
> [1/4] Resolving packages...
> warning jvectormap@1.2.2: jvectormap is not maintened since Aug 2015. You can use jvectormap-next or jqvmap instead.

**Comment by marcelogarbin** [comment]
@brot any news?

here:

> $ yarn install
yarn install v1.2.1
info No lockfile found.
[1/4] Resolving packages...
warning admin-lte > jvectormap@1.2.2: jvectormap is not maintened since Aug 2015. You can use jvectormap-next or jqvmap instead.
error An unexpected error occurred: "https://registry.yarnpkg.com/chart.js: ETIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/home/vagrant/Code/estrutura/L5.5/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by ldynia** [comment]
Please upgrade your `admin-lte` to the latest version.  It should work with `"admin-lte": "^2.4.15",`
