### ISSUE TITLE
less compilation failing on 2.4 when using skins

### ISSUE THREAD

**Issue by boodle** [ColorlibHQ/AdminLTE#1675]
Related to issue #1665, we are getting compilation failures when using a skin, when installed via npm.

Error:
```
Running "less:dist" (less) task
>> FileError: '../../../bower_components/bootstrap/less/mixins.less' wasn't found. Tried - node_modules/admin-lte/bower_components/bootstrap/less/mixins.less,node_modules/admin-lte/bower_components/bootstrap/less/mixins.less,../../../bower_components/bootstrap/less/mixins.less in node_modules/admin-lte/build/less/skins/skin-blue.less on line 5, column 1:
>> 4  */
>> 5 @import "../../../bower_components/bootstrap/less/mixins.less";
>> 6 @import "../../../bower_components/bootstrap/less/variables.less";
Warning: Error compiling node_modules/admin-lte/build/less/skins/skin-blue.less Use --force to continue.
```

[Line in question](https://github.com/almasaeed2010/AdminLTE/blob/master/build/less/skins/skin-blue.less#L5)

**Comment by Oleg-Arkhipov** [comment]
No fix for that from @almasaeed2010 ?
My only option is to do `bower install` in `node_modules/admin-lte`? Seems really broken.

**Comment by mmrodriguez1987** [comment]
Hi @Oleg-Arkhipov 

It seems that @almasaeed2010 still the issue in NPM Repository, and he forgot to change the result of the folder "build" the only thing you have to do is copy from the AminLTE GIT repository the "Build" folder and paste it into "yourproject / nod_modules / admin-lte /", this will replace them all the code of the build folder.

Note: do not run "npm update" because if you do, npm will rewrite the folder with the error that @almasaeed2010  has not yet fixed in NPM

**Comment by kspearrin** [comment]
Having this same issue now after updating from 2.3
