### ISSUE TITLE
Multilevel collapse not working for child tree menu

### ISSUE THREAD

**Issue by krukas** [ColorlibHQ/AdminLTE#1697]
**Steps to reproduce:**
1) Open multilevel menu item
2) open child menu from multilevel
3) close or click on other main menu item
4) Reopen multilevel menu

**Expected result**
A) Child menu's are closed
B) Child menu's are open and click them to close

**Actual result**
Child menu's are open, but on the first click nothing happens and on the second click it's closing.

I looks like the (display: block) isn't removed from the child tree menu. I will create a pull request that fixes this, but I don’t think and now if this is the best/beautiful solution.

**Comment by rihlsul** [comment]
Took me a long time to sort this out due to jQuery rookie level.  The above did not do what I needed.  Not sure why, but `link.next(Selector.treeviewMenu)` was only returning the first child (call it 1.2) in the multilevel tree, leaving the others open.  If I opened main menu (2.0), then 1.x all collapsed fine.

What I needed was this:
https://imgur.com/a/gQuSb

From Tree.js, line 55.  First line included for context, as well as commented original = on the 2nd line.
```javascript
Tree.prototype.toggle = function (link, event) {
    var treeviewMenu = link.parent().children(Selector.treeviewMenu) //link.next(Selector.treeviewMenu)
```

Since I'm not sure the way I've re-written mind is the intended functionality, I have not done a pull on this.

**Comment by krukas** [comment]
Hi @rihlsul,

I think your comment is for a different issue.

**Comment by alextech** [comment]
I would put class removal into slideUp callback so animation would not be so jerky. Now it removes class, leaves a gap, then animates over the gap. Let it animate while all is visible, then remove class when all complete.

Also, create pull requests as early as possible. Easier to discuss code in the code review UI that PRs give for maintainer and others.
