### ISSUE TITLE
AdminLTE conflicts with vue that comes with laravel

### ISSUE THREAD

**Issue by allaghi** [ColorlibHQ/AdminLTE#1802]
I am wondering why I can't use vue that comes with laravel , I think there is issue with adminlte

**Comment by almasaeed2010** [comment]
The issue is that webpack requires a specific way to set the path of assets in LESS. So it's failing to figure out where the boxed-bg image is. If you or anyone finds a way to make this work cross platform, I will implement the solution in AdminLTE. So far, I am not aware of a way that allows this to work for WebPack and not fail everywhere else.

Thanks

**Comment by andrewboy** [comment]
The fast (and not the best) solution is to use this setting:

```
mix.options({
  processCssUrls: true,
  imgLoaderOptions: {
    enabled: false,
  }
});
```
I got it to work.
In my case (with Laravel) a binary file compile is failed on npm install and caused this "I don't find that  boxed-bg image" issue. 

After running 

`npm rebuild mozjpeg`

turned out that nasm is missing from the server. After install the compile works as a charm.
