### ISSUE TITLE
Drag and drop breaking adminlte's design 

### ISSUE THREAD

**Issue by RaruRv** [ColorlibHQ/AdminLTE#1924]
### Environment:
* AdminLTE Version:  2.4.3
* Operating System:  Ubuntu 16.04
* Browser (Version): Chrome

If we drag the elements and move towards the right side, It will break the design of the template. It is breaking the style of the right side bar.
https://adminlte.io/themes/AdminLTE/index.html

**Comment by davejamesmiller** [comment]
I think I can reproduce this - if the right sidebar is **hidden**, dragging to the right edge of the screen shows the sidebar and then continues to scroll right. When you let go, the right sidebar is shown and the left is hidden because the scroll position is not reset.

![image](https://user-images.githubusercontent.com/236616/42737957-b1595a1e-8873-11e8-82fa-ff4ef34c63a3.png)

I think the `containment` option would fix this.

http://api.jqueryui.com/sortable/#option-containment

**Comment by RaruRvt** [comment]
kidoos. Thanks for solving the issue.
