### ISSUE TITLE
navbar dropdown-menu in skin-blue-light has white text on white background

### ISSUE THREAD

**Issue by hendimarcos** [ColorlibHQ/AdminLTE#1933]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  v3.0.0-alpha.2
* Operating System:  All
* Browser (Version):  All

### Description:
When I change the skin of the header to someone who has the navbar-dark class, the font colors in the notification dropdown and messages are the same background color.

![image](https://user-images.githubusercontent.com/910965/42740140-587affa0-8879-11e8-99e1-54f4a7a09ff5.png)

![image](https://user-images.githubusercontent.com/910965/42740143-65d5f952-8879-11e8-84cf-323a22770417.png)

**Comment by almasaeed2010** [comment]
Thanks for reporting @hendimarcos

**Comment by REJack** [comment]
I've changed AdminLTE according to close this issue,

instead of `bg-*` you can now add the following classes to the navbar and you can combine them with `navbar-dark`or `navbar-light`:
- `navbar-primary`
- `navbar-secondary`
- `navbar-success`
- `navbar-info`
- `navbar-warning`
- `navbar-danger`
- `navbar-blue`
- `navbar-indigo`
- `navbar-purple`
- `navbar-pink`
- `navbar-red`
- `navbar-orange`
- `navbar-yellow`
- `navbar-green`
- `navbar-teal`
- `navbar-cyan`
- `navbar-white`
- `navbar-gray`
- `navbar-gray-dark`

You can test this on my demo space http://adminlte-dev.rejack.space/
