### ISSUE TITLE
Hide main.header .logo for mobile

### ISSUE THREAD

**Issue by bxs3zo1992** [ColorlibHQ/AdminLTE#2041]
Hello,
Thank you for the opensource code, probably the most amazing free out there. I know this has been asked before but had no answers unfortunately.

The main header for mobile sizes is double the size because there are two classes in the main-header.
![2](https://user-images.githubusercontent.com/41914141/50096714-3e54fc00-0210-11e9-9031-625bdf41d26c.jpg)

I want to make it only one as the following:
![1](https://user-images.githubusercontent.com/41914141/50096742-4ca31800-0210-11e9-96ce-41fde953a119.jpg)

Can someone please advise on best practice to hide main.header .logo for mobile?

or combine both the class navbar and class logo so both are in the same main-header. As now they are separated?

Issue type:
- [X ] Feature request 
- [ ] Bug report       
- [ ] Documentation   

Environment:
* AdminLTE Version:  2.4
* Operating System:  Windows 10
* Browser (Version):  Chrome (Latest)

**Comment by heemza** [comment]
Due to AdminLTE v2 using Bootstrap 3 you can use bootstrap available css class to hide it by adding 'hidden-xs' for phone  and/or 'hidden-sm' for tablet.
(details: https://getbootstrap.com/docs/3.3/css/#grid)

`<div class="main-header"><a href="index2.html" class="logo hidden-xs hidden-sm">
    <span class="logo-mini"><b>A</b>LT</span>
    <span class="logo-lg"><b>Admin</b>LTE</span>
</a>....</div>
`

Result will be like this:
<img width="394" alt="screen shot 2018-12-22 at 12 15 05" src="https://user-images.githubusercontent.com/6562562/50370945-47184a00-05e3-11e9-92a0-4bc35ea60c94.png">
