### ISSUE TITLE
Question: How to Make Font-Awesome Working while Offline?

### ISSUE THREAD

**Issue by kuswantoheng** [ColorlibHQ/AdminLTE#2090]
Hello all,

How to Make Font-Awesome Working while Offline?

I am a newbie. Sorry for the dumb question.

**Comment by jfcaldeira** [comment]
reference font awesome scripts locally and not from a link

**Comment by kuswantoheng** [comment]
where is the location of the link?

here is the attachment that shows the font size is getting bigger while running offline. any help would be appreciated :)

![image](https://user-images.githubusercontent.com/25238476/56087023-f6c44100-5e8c-11e9-847e-b256d8433fdd.png)

if i run it online, here is the display

![image](https://user-images.githubusercontent.com/25238476/56087030-1ce9e100-5e8d-11e9-9d80-66a2a4b0206e.png)

**Comment by ariaenggar** [comment]
Here's how you do it now:
`<link rel="stylesheet" href="https://fonts.googleapis.com?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
Since https://fonts.googleapis.com?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic is a css file, you can download it, and reference it locally in your index.html
`
Here's an example how you do it from local:
   ` <link rel="stylesheet" href="assets/css/fontsgoogleapis.css">
`

**Comment by kuswantoheng** [comment]
I found the link in AdminLTE.css that reference to Google Font. I did replace it and it works!

Thanks all.
