### ISSUE TITLE
adminLTE v2 IE下点击左侧菜单树子菜单图标问题

### ISSUE THREAD

**Issue by lxdreamer** [ColorlibHQ/AdminLTE#2140]
### Issue type:
- [ ] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):  

### Description:
ie下点击左侧菜单下面的子菜单的icon图标会消失，鼠标移动下又出现了，
谷歌下无此问题

**Comment by lxdreamer** [comment]
![menu](https://user-images.githubusercontent.com/19904820/59987142-3c12a500-966c-11e9-9c08-6e2351538d24.gif)

**Comment by REJack** [comment]
Sadly I don't find a fix for IE11's behavior, it looks like a issue from FontAwesome self. I doesn't get the issue with FontAwesome 5.

**Comment by sudo-barun** [comment]
I am also facing this problem when using AdminLTE 2.4.18 in Edge browser. I have found that this problem occurs only when using the **fixed layout** of AdminLTE (like in: https://adminlte.io/themes/AdminLTE/pages/layout/fixed.html).

I followed the suggestion from @REJack and used FontAwesome 5.9.0 instead of 4.7.0, but it does not work.

If anyone has a proper solution, please mention it in a comment.

**Comment by linhdn-0941** [comment]
I also have the same problem. The reason is that the sidebar treeview uses the slideDown, slideUp animations, to open and close the sub-treeview. But the :before :after pseudo does not support IE when mix with animations https://developer.mozilla.org/en-US/docs/Web/CSS/::before.

I have replaced it with html symbols `&cir;` https://dev.w3.org/html5/html-author/charref and css for same with icon `fa fa-circle-o`.

`<i class="custom-icon">&cir;</i>`

![cir](https://user-images.githubusercontent.com/53817648/114005278-986aa700-9889-11eb-942d-b027c0f6aa80.gif)
