### ISSUE TITLE
BUG: Chart can disappear inside the card 

### ISSUE THREAD

**Issue by Zanoshky** [ColorlibHQ/AdminLTE#2145]
### Issue type:
- [x] Bug report      

### Environment:
* AdminLTE Version:  Admin LTE 3 Beta
* Operating System:  Any
* Browser (Version):  Latest Chrome  / Latest Firefox

### Description:
- Put a Chart inside a Card
- Add MAXIMIZE data-widget to card toolbar

- Steps to reproduce:
1. Click the MINUS button to collapse the chart.
2. Press the maximize button (to go full screen)
3. Press the maximize button (to minimize the chart back to default)
4. Press the PLUS button to expand the chart.
5. The chart is missing.

Sorry for long gif.

![bugReport](https://user-images.githubusercontent.com/8194241/60258844-3fa96480-98d6-11e9-8310-bc29dc4d19f0.gif)

**Comment by REJack** [comment]
I've found the bug, ChartJS resizes the canvas and set height to 0 caused by collapsed box, the chart disappear on collapsing too.
I found only a workaround for this 😞 I've added min-height to the demo chart canvas', my areaChart canvas looks like this `<canvas id="areaChart" style="height:250px; min-height:250px"></canvas>`.
