### ISSUE TITLE
Sticky -dragable event is not working properly in fixed layout

### ISSUE THREAD

**Issue by saileshkush95** [ColorlibHQ/AdminLTE#2168]
### Issue type:
- [x] Feature request  => Page loader
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  Latest V3
* Operating System:   Linux(Kde Neon)
* Browser (Version):   Latest Chrome

### Description:
Dragable event is working fine in all layout except fixed layed. Please also include animated page loader to make this project more professional, but this is optional.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/28560875/61195327-04d16a00-a6e7-11e9-883b-c196fb2df4c9.gif)

**Comment by REJack** [comment]
Oh dang the zindex is not ok :/
Do you mean pace-progress as animated page loader?

**Comment by saileshkush95** [comment]
Sorry I didn't understand what you are trying to say but I mean Display a loading icon until the page loads completely.  Such as
http://www.instantshift.com/2016/01/22/free-html5-css3-loaders-preloaders/

In the a above giff sticky dragable event also over flow above header navbar, it's not the problems only related to z index. Thanks 😊 for your quick response.

**Comment by REJack** [comment]
I know the navbar is related to the top offset you need to set of your own, you need to set style="top: 77px;" beside .sticky-top I can’t set it in general because you should set it depending on your situation 😄  the sidebar issue is related to zindex navbar use something around 800+ and the sticky use 1000+ I need to set the zindex for this correctly. 
I

For animated loading icon or loading bar look over https://github.hubspot.com/pace/docs/welcome/, it‘s already packed in AdminLTE but we don‘t have any demo for this.

**Comment by saileshkush95** [comment]
Thanks and lost of love from Nepal.

**Comment by REJack** [comment]
I've added a fix for the overlapping issues in my fork, its coming with the docs in my next PR.

**Comment by REJack** [comment]
This issue is merged with my PR #2169
