### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Leviasan** [ColorlibHQ/AdminLTE#2262]
### Description:
I am writing my project based on yours. 
Together, I use a typescript code instead of javascript.
Do you somewhere have an inventory of all js objects in typescript?

**Comment by REJack** [comment]
For which version v2.4 or v3.0?

**Comment by Leviasan** [comment]
For  v3.0

**Comment by REJack** [comment]
I doesn't use typescript and I don't know how to create this support, but you can create a PR for this 😄.

**Comment by Leviasan** [comment]
Omg 😄. If it will be boring in my free time, I will make a declaration files.

**Comment by hktr92** [comment]
btw, it would be nice to have native typescript support for v4. if that's the case, i could help up with refactoring.

having native ts code would prevent the need of `d.ts` file, which offers only an interface and no access to implementation details for js files. i often got frustrated because of this one.

also, having ts support would benefit vue 3, which is written in ts, plus the nuxt-ts project (also in typescript).

**Comment by REJack** [comment]
I will rework the JS Plugins in Typescript since I use it in many projects and like the benefits 😄

**Comment by danny007in** [comment]
done in https://github.com/ColorlibHQ/AdminLTE/tree/v4-dev
