### ISSUE TITLE
I have issues with sidebar and table

### ISSUE THREAD

**Issue by muhammadarsalansiddiqui** [ColorlibHQ/AdminLTE#2263]
### Issue type:
- [x] Feature request 
- [x] Bug report

### Environment:
* AdminLTE Version:  AdminLTE v3.0.0-rc.1
* Operating System:  Windows 10 x64
* Browser (Version):  76.0.3809.132 (Official Build) (64-bit)

### Description:
1) I want to remove customize pane of adminlte and want a predefined color of nav bar, sidebar, brand logo. I have tried looking in demo.js but i can only change color of navbar but then font color is turn blue.

2) I want to completely hide sidebar

3) I want to turn off hover effect on sidebar

4) When i minimize side bar, table will not expand

![AdminLTE 3fgdfgdf   DataTables](https://user-images.githubusercontent.com/36761603/64480088-bb7b3380-d1da-11e9-9dfd-3b4929c82afe.png)

![AdminLTE 3ty54egbdfbdb   DataTables](https://user-images.githubusercontent.com/36761603/64480100-f2e9e000-d1da-11e9-8bb4-5b12ba491be7.png)

5) Customize adminlte right bar do not display on mobile screen

6) I want default behavior set to closed of sidebar

**Comment by REJack** [comment]
1. The customizing tool on the right in the demo is only for an demo how you can use the control sidebar. 
If you want to change the color of Sidebar Active state change `sidebar-dark-primary` to any other color/theme-color (e.g.  `sidebar-dark-danger` or `sidebar-dark-lime`) a complete color list can found in the [docs](https://adminlte.io/docs/3.0/layout.html)
for navbar you can replace `navbar-white` with `navbar-*` (again all color/theme colors useable) you can also combine `.navbar-*` with `.navbar-light` or `.navbar-dark` to get changed font color.
for brand-link you can also add `.navbar-*`.
Which font turned blue?

2. remove the `sidebar-mini` class from `body`
3. add `sidebar-no-expand` class to `.main-sidebar`
4. You need for this datatables responsive plugin css/js, make sure that you load this files and enable the option.
5. This bug is already fix in my PR #2256 and will come with rc.2
6. Add `sidebar-collapse` class to `body`

**Comment by REJack** [comment]
Please provide the html code from you image example (4.)

**Comment by muhammadarsalansiddiqui** [comment]
Fixed, i've missed **autoWidth: false**
Thanks
