### ISSUE TITLE
Taiwan is not a country, it belongs to China.

### ISSUE THREAD

**Issue by zhao-tan** [ColorlibHQ/AdminLTE#2335]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):  

### Description:
![image](https://user-images.githubusercontent.com/52996377/66984429-44945d00-f0ed-11e9-95b3-43a6efdc7dd5.png)
![image](https://user-images.githubusercontent.com/52996377/66984460-54ac3c80-f0ed-11e9-8a73-f2dacf072b0d.png)

https://adminlte.io/themes/AdminLTE/index2.html

**Comment by andcarpi** [comment]
This is not a problem with the package. That map is just an external plugin, in an example page...

**Comment by malle-pietje** [comment]
@zhao-tan Make sure you understand what you are talking about when submitting a complaint like this. This is where the map is being sourced from:
http://jvectormap.com/

**Comment by firstrose** [comment]
@zhao-tan 去 https://github.com/bjornd/jvectormap 提issue好了，他们主页地图上亚洲有台湾，中国没台湾。明显是他们数据问题。

@malle-pietje  AdminLTE uses an outdated version of jvectormap, why not update it? :)

**Comment by malle-pietje** [comment]
I don't see that as the responsibility of the AdminLTE package maintainer, especially since this is with version 2. You can easily update this yourself if it's important.

By the way, did you take the time to check when the last update was applied to that specific package? Let me tell you that that was 4 years ago...
https://github.com/bjornd/jvectormap/

There's nobody stopping you from forking the repo and applying the updates yourself...

**Comment by andcarpi** [comment]
The thing is... the author is working on version 3... he also stated (don't remember where) that version 2 will not receive a new jsvectormap, because it's a breaking change in the adminlte 2...

**Comment by peerct** [comment]
死五毛，回家学学历史去，中国民国台湾108年了，谁在搞分裂！

**Comment by REJack** [comment]
It's all discussed here already, jvectormap is an external plugin we don't modify it so ask it on the official repo to fix this. 
Also I'll not replace jvectormap to avoid breaks by users after the release is to long out there, like @andcarpi wrote it already 😄 .
