### ISSUE TITLE
Download location cyclic

### ISSUE THREAD

**Issue by stevehomer** [ColorlibHQ/AdminLTE#2372]
### Issue type:
- [x] Bug report       
- [x] Documentation   

### Environment:
* AdminLTE Version:  ALL
* Operating System:  N/A
* Browser (Version):  N/A

Trying to move to later version (site built on 2.3.5!) Git says go to https://adminlte.io/ for download that sends you back to https://github.com/ColorlibHQ/AdminLTE/releases.  

Documentation page for 2.3.x  and 2.4.x says to download a: "Ready" (compiled) version or a "Source Code" (non-compiled - need LESS) version.

As I am NOT au fait with LESS and Node (or whatever) I am a bit flummoxed. All downloads available named "Source Code".

AdminLTE is a great beginner theme. 

So are the versions I am downloading in need of compiling? Also pls see separate note re problems with starter.html.

In passing thanks a million for a nice, clean easy to use theme that is free.

Steve

**Comment by REJack** [comment]
> Trying to move to later version (site built on 2.3.5!) Git says go to https://adminlte.io/ for download that sends you back to https://github.com/ColorlibHQ/AdminLTE/releases.

I'll update the readme in next days.

> Documentation page for 2.3.x and 2.4.x says to download a: "Ready" (compiled) version or a "Source Code" (non-compiled - need LESS) version.

In the docs for v2.3.x I see it but they are not important, in the v2.4.x docs I can't see the info text with compiled and non-compiled. AdminLTE delivers the compiled dist files in all releases since v2.4, you can use the source code to modify/compile by your own or you can use the compiled dist files.

**Comment by stevehomer** [comment]
Thanks for that. I will go and try 2.4.18.

In passing mind you...

AdminLTE is great because it is **comparatively** simple. That means you are getting a fair number of novices (idiots???) trying to use it.

> In the docs for v2.3.x I see it but they are not important

You may say that but this caused me to lose quite a chunk of time trying to work out what was going on.

The 4.3s say "Source Code" files need a LESS compiler. So looking at the latest version (`2.4.18`) I spent well over an hour reading about LESS and trying to find stuff on YouTube etc. Then started downloading various versions trying to work out what was going on. All in all about 2.5 hours.

I have had to "learn" HTML, CSS, JavaScript, jQuery, Bootstrap, MySQL, Apache (some), PHP, PhpStorm (almost a language) plus a couple of others.

I have NOT learnt Composer, Bower, NPM, Laravel, Moustache, Blade, Handlebars, LESS, SASS, Ruby, Python  plus many others. All these technologies I have had a quick look at and run away from as I have to get on with cranking out another alpha/beta project. 

If there is an easy way to tweak all the 2.3s to point at the latest 2.3 versions (with Source Code and the other one) that would be great. The 2.4s make no allowance for idiot users which is a pity.

I have a shared hosting set up and have never managed to work out how to sort out out Composer, NPM or whatever and how it relates to the server. All I want is a simple, jQuery/Bootstrap theme that I can edit.

Sorry to go on but I hope you can understand what I mean.

We idiots would really appreciate a dumbed down installation guide.

But as I keep saying a million thanks for all the work that everyone has put in on this!

**Comment by REJack** [comment]
> EDIT: Just realised the 2.4s still say Ready vs Source Code so the confusion continues.

Where you see this?

> If there is an easy way to tweak all the 2.3s to point at the latest 2.3 versions (with Source Code and the other one) that would be great. The 2.4s make no allowance for idiot users which is a pity.

Since v2.4.0 is released the v2.3 docs are not update and it has changed multiple times also 2.3 doesn't get any update since 3 years so it will remain as it is and may I will remove it anyway with new webpage.

> I have a shared hosting set up and have never managed to work out how to sort out out Composer, NPM or whatever and how it relates to the server. All I want is a simple, jQuery/Bootstrap theme that I can edit.

You can also compile it on your local machine, I've added a small instruction for compiling the dist files. You will always need npm for the default behavior.

>  EDIT: PS: 2.4.x has a more complicated structure than 2.3.x. We now have bower_components, dist, build and plugin directories. In the index example files dist, bower and plugin files are used. I know this is an idiot question but for novices an explanation of which directories (and sub directories eg: C:\xampp\htdocs\ata.test\AdminLTE-2.4.18\dist\css\alt\AdminLTE-fullcalendar.css) to use would be very helpful

1. I don't know why the bower_components & the plugins folder exists but I always used the files from the bower_components folder, since the v3 developing was near to end I stopped to enhance v2.4 with new stuff so it will remain also.
2. AdminLTE-fullcalendar.css, AdminLTE-bootstrap-social.min.css & AdminLTE-select2.min.css are only needed with AdminLTE-without-plugins.min.css to get the custom styles.
