### ISSUE TITLE
[BUG] Wrong documentation link for icheck-bootstrap

### ISSUE THREAD

**Issue by cataclysmuprising** [ColorlibHQ/AdminLTE#2506]
**Describe the bug**
Documentation link at **Forms > Advance Elements > iCheck Bootstrap - Checkbox & Radio Inputs** is wrong. This should be https://bantikyan.github.io/icheck-bootstrap/ instead of http://icheck.fronteed.com/ . They are completely different ones.

**Additional context**
I do prefer [icheck](http://icheck.fronteed.com/) than [icheck-bootstrap]( https://bantikyan.github.io/icheck-bootstrap/) because it has a lot of features to control from javascripts , plenty of callback methods and well documented. It does not need to have `<label>` element and `id` attribute like [icheck-bootstrap]( https://bantikyan.github.io/icheck-bootstrap/) . Although it is  little outdated, I can't find other checkbox and radio library better than this yet.

**Comment by REJack** [comment]
Thanks for the report 😄 I've fixed it in master repo.

My biggest concern was the stale state of the icheck project that's why I replaced it with icheck-bootstrap, also I wouldn't add it back (in order to get the template slowly jquery free). But the style overrides should still work, you only need to load the icheck's css before adminlte's css.
