### ISSUE TITLE
[BUG] Image not changing in product image of examples/e_commerce.html

### ISSUE THREAD

**Issue by bansalshashank** [ColorlibHQ/AdminLTE#2510]
**Describe the bug**
When clicked on product image thumb the product image should change with the respective image but it's not

**To Reproduce**
1. Go to 'https://adminlte.io/themes/dev/AdminLTE/pages/examples/e_commerce.html'
2. Click on product thumb image under the product image
3. The image should change with the clicked product image thumb but it's not

**Expected behavior**
On clicking the product image thumb the product image should replace with the product thumb image 

**Environment (please complete the following information):**
 - AdminLTE Version: [3.0.3-pre]
 - Operating System:  [Ubuntu 18 bionic]
 - Browser (79.0.3945.130): [Chrome]

**Comment by bansalshashank** [comment]
#2509

**Comment by REJack** [comment]
Thanks for the Issue, PR is merged 😄

**Comment by bansalshashank** [comment]
Thank you for the merge

**Comment by iaguas** [comment]
I want to make a suggestion. With #2509, products changes as it should be, but there is a little problem if all images are not of the same size, as the mountain boot in the example page. In these cases, the little gallery change of place (different distances) because it is placed after the image. 

For this reason, I propose to put the gallery in a distance equal as the greater one of images. For the other images which are small, I will propose to center the image in the vertical axis.

Thank you in advance.
