### ISSUE TITLE
Adding more than 20 Fields in the registration page [BUG]

### ISSUE THREAD

**Issue by Tikbalang** [ColorlibHQ/AdminLTE#2563]
**Describe the bug**
The card centers vertically which hides the top most part of the form when we added more than 20 fields in the registration page. It is somehow coming from the 'class="register-page"' in the body tag.

**To Reproduce**
Add more than 20 fields (more than enough to fit the screen vertically)

**Expected behavior**
The form should be aligned at the top and all the fields can be accessed by scrolling downwards.

**Screenshots**
![image](https://user-images.githubusercontent.com/22811280/75092383-e9e6a280-55b1-11ea-862d-20b15ec76ab5.png)

**Environment (please complete the following information):**
 - AdminLTE Version: 3.0
 - Operating System:  Windows 10
 - Browser (Version): Version 79.0.3945.130 (Official Build) (64-bit)

**Additional context**

**Comment by picks44** [comment]
+1 on this!!

**Comment by REJack** [comment]
I can't replicate this even with the online demo, if you add `class="register-page"` it should work but make sure you loaded the adminlte(.min).js in the register page.

I've added this fix before releasing AdminLTE v3.0.0.

**Comment by picks44** [comment]
Hi @REJack, my register form is using `class="register-page"` on the `body` tag just like on the demo. and also has adminlte(.min).js.
Because my form is pretty long, I'm using a JS wizard that creates steps on my form. Each step has a different size, but even if I tried to lower the height of each of them, for the longuest ones I'm having the same issue spotted above. 
The top of the form is not reachable by the user, which is a major issue. Same issue when my form has errors, the addition in JS of the error message below the fields adds height to the whole step and ends up with the same issue of "cropping" the form.
![1](https://imgur.com/hwdjISJ)
![2](https://imgur.com/NZK1gln)

**Comment by picks44** [comment]
I'm tried tweaking the CSS a little bit, and updating as 
```
.register-page {
  align-items: flex-start;
  flex-direction: row;
}
```
instead of 
```
.register-page {
    align-items: center;
    flex-direction: column;
}
```
seems to solve the problem, even if the form is no longuer vertically centered...

**Comment by REJack** [comment]
@picks44 Instead of your CSS tweak you can also only run $('body').Layout() after content change (validation or step change). 

I've enhanced the script to correct the layout automaticly without run the layout script, for this you can add `data-login-register-auto-height="100"` on body to correct it in an 100ms interval instead of single correction on load.

**Comment by picks44** [comment]
Hi @REJack, cool I'll try that ASAP and let you now!
Thanks for this quick support!

**Comment by picks44** [comment]
Hi again @REJack, I've triggered `$('body').Layout();` on step change, but it doesn't solve the issue, unfortunaltely. I can see that the `min-height` property is being regenerated on each step change, but the top of my form is still not reachable.

**Comment by REJack** [comment]
To test the new option you will need to download/clone the master branch via github.

Is your logo placed inside the register-box?

**Comment by picks44** [comment]
@REJack I'm using a package manager on my prpject (yarn/npm) so it won't work until there is a new release I guess.
My logo is placed above the `card` in the `register-logo` div, just like in the example:
```
<div class="register-box">
    <div class="register-logo">
        <img src="logo.jpg" class="img-fluid" alt="">
    </div>
    <div class="card">
    </div>
</div>
```
