### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by judodan** [ColorlibHQ/AdminLTE#2864]
Is there a reason *ALL* the used libraries have to be distributed with the repo?

I'm including this in a PHP project via composer, and there is an INCREDIBLE number of [usually very small] files, so it takes an immense amount of time when  transferring a site from staging to production. Do we really need to include exact versions of a library that can be exactly specified by a CDN?

Just curious if there was an upside to that. Maybe have branches for both methods?

**Comment by arcanisgk** [comment]
I understand your point of view, but it seems to me that this template is designed to work with specific library versions, and thus prevent an update from causing something to stop working correctly, even from an intranet without internet; in that case the CDNs would not make sense.

What I can also tell you is that if you are working with pure php or under a framework, and you have to upload the entire project every time you make a change to a couple of files, you have a bad implementation of your version control.

In my case, since I have a personal project, I usually use VSCode that allows me to staged to a specific file, and then make the local committee when finished and finally upload my local committee to the `git push origin master --force` repository, and So only upload the modified files and not the whole project.

**Comment by judodan** [comment]
Thanks for your response.

I understand the case of an intranet, that makes sense, but if you're not on an intranet, a CDN can make sense. You specify the version of the library you're using, so it's not going to suddenly change on you.

I'm also only updating modified files, but when a new version comes, if a library changes (say something big like ckeditor), it could means hundreds (or more!) of files that are changing.

Granted, my case was more extreme than normal, but I upgraded from a 2.3.x version to 2.4.18. When I pushed (only the modified files) to production, it took almost an hour. Sure, it's a one time thing, but who wants production down for an hour if it could only be a minute or 2?

I am contemplating this as I look forward to 3.x, which will likely have a LOT of modified files.  If your situation is different, and you NEED all the libraries local, I can understand that, but as I said, a branch using both methods might be a good compromise.

**Comment by arcanisgk** [comment]
I don't see any sense, it takes 1 ~ 2 hours; unless you are programming with a dial up connection

**Comment by REJack** [comment]
You can get rid of the files even after composer update with an simple plugin called [composer-vendor-cleaner](https://github.com/liborm85/composer-vendor-cleaner), also we distribute all the plugins in composer to give the composer users the chance to use all plugins without any extra work many of the used plugins are not distributed on composer either.
