### ISSUE TITLE
[FEATURE] - Make AdminLTE v3 compatible with https://bootswatch.com/

### ISSUE THREAD

**Issue by distributev** [ColorlibHQ/AdminLTE#2976]
This way AdminLTE v3 will get the bootswatch.com Theme switcher with +20 themes variations (including https://bootswatch.com/materia/ which is inspired by Material Design)

**Describe the solution you'd like**

Here https://github.com/ColorlibHQ/AdminLTE/issues/1484 @almasaeed2010 said that AdminLTE v3 and bootswatch.com integration should work almost out of the box because AdminLTE v3 will closely respect all the Bootstrap 4 variables (which boots watch is also using to customize bootstrap).

However in this more recent thread https://github.com/ColorlibHQ/AdminLTE/issues/2436 @REJack said that this is not possible to do in AdminLTE v3.

Is this integration possible? If so, do you consider adding some documentation for users to understand how this can be done?

**Describe alternatives you've considered**

Try to combine myself AdminLTE3 and bootswatch using Sass (both projects are using sass).

**Comment by dwasyl** [comment]
Bootswatch seems to generate both cusotmized CSS and Sass files. I would think you could just download the Sass (.scss) files and include them in your AdminLTE scss Sass file to be compiled in.

That said, you need to be running your site based on the AdminLTE Sass rather than the distributed css files.

This isn't documentation, but all you'd do is download the scss files that Bootswatch generates, then include them as part of the AdminLTE.scss file. Documentation might be tough since it will really depend on your front end toolchain. It also likely needs some testing to see if it causes any problems, but if all it does is override some bootstrap defaults it shouldn't be an issue.
