### ISSUE TITLE
[BUG] js has error if  sidebar without search

### ISSUE THREAD

**Issue by yangfuhai** [ColorlibHQ/AdminLTE#3008]
error message:

```
SidebarSearch.js:161 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at e.n._renderItem (SidebarSearch.js:161)
    at e.n._addNotFound (SidebarSearch.js:194)
    at e.n.init (SidebarSearch.js:76)
    at w.fn.init.e._jQueryInterface [as SidebarSearch] (SidebarSearch.js:212)
    at SidebarSearch.js:274
    at dispatch (jquery.min.js:2)
    at y.handle (jquery.min.js:2)
```

**Comment by mineminemine** [comment]
Is this  your own implementation or some third party plugin for searching? I can't recall AdminLTE having such feature as of v3.x. If yes then I don't think this github page is the place to seek help for this issue.

I'm guessing you're actually filtering the sidebar items to search for something specific in the sidebar? Then the error above likely happened because the search function was triggered on page load instead of having an event listener on the input field as the user is typing. Otherwise, you might be supplying the wrong parameter for the function.

**Comment by yangfuhai** [comment]
the error reason is  remove the searchform code below.

```
      <!-- SidebarSearch Form -->
   <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div> 
```

**Comment by yangfuhai** [comment]
the login.html page has the error too, because it has not the  "sidebar-search" widget.

**Comment by mineminemine** [comment]
Sorry I actually just found out that the latest commit does include a sidebar searching.
The problem you found is actually referenced in #2841 and is still a persisting problem.

However there are a few ways to fix this problem:


1. By removing the import and export for the `SidebarSearch` in /build/js/AdminLTE.js which in effect will remove sidebar search functionality sitewide
2. In SidebarSearch.js, add the following lines after init() like this: ![1](https://user-images.githubusercontent.com/17585549/92573052-d08c1600-f2b7-11ea-88a8-480070282b06.png) which will then still allow you to have sidebar searching when `data-widget="sidebar-search"` is set.

The choice is up to you of course.

**Comment by REJack** [comment]
PR Merged 😄
