### ISSUE TITLE
DataTable: dropdown (responsive) doesn't execute my jquery 

### ISSUE THREAD

**Issue by julianamariel** [ColorlibHQ/AdminLTE#3016]
Hi, I have this code for execute a function when <a> was clicked. The code works fine in pc view but it doesn't call the jquery in responsive design.

```
<a href="#" data-id="<?php echo $admin['id_admin']; ?>"  class="btn btn-outline-danger bnt-flat margin eliminar-registro">
                              <i class="fas fa-trash"> </i>
</a>
```

```
 $('.eliminar-registro').on('click', function(e) {
      var id = $(this).attr('data-id');
      and sweet alert code
 });
```

Normal: https://ibb.co/bHxMWCf
Responsive: https://ibb.co/4NdvMhb (nothing happens) 

I would appreciate it if someone could help

**Comment by REscobar** [comment]
This issue is caused by the way DataTables handles the responsive view, probably it is removing and re-adding the columns that should not be visible thus causing the anchors (`a` tags) to loose their events.

There are many ways to avoid this issue, some of them are documented in the DataTables help, probably in the column factory section, but I believe the simplest approach would be enough and that would be to do delegated events on child elements, check the second code example on [jQuery docs](https://api.jquery.com/on/) for the `on` function.

If you still have trouble, post the html code used to create the table.

**Comment by mineminemine** [comment]
As @REscobar mentioned, this is probably caused by how datatables renders the table in responsive view which in turned likely bugged out the event listener.

One way I could think of to fix this is by adapting the onClick attribute on the anchor tags and change your JQuery function to a normal Javascript function.

**Comment by julianamariel** [comment]
Thanks!!!!!!!!!! I fixed the problem using delegated event

`$('.card-body').on('click', '.eliminar-registro', function(e) {`
