### ISSUE TITLE
[BUG] in v3.1.0-rc dark-mode and other

### ISSUE THREAD

**Issue by danny007in** [ColorlibHQ/AdminLTE#3166]
![Screenshot 2020-11-29 113611](https://user-images.githubusercontent.com/50356015/100534643-3b097e00-3237-11eb-87b2-c2a568127b07.gif)
![Screenshot 2020-11-29 112038](https://user-images.githubusercontent.com/50356015/100534644-3c3aab00-3237-11eb-85eb-dd6794c8ef3a.gif)
![Screenshot 2020-11-29 112230](https://user-images.githubusercontent.com/50356015/100534645-3d6bd800-3237-11eb-9968-435d66cda7df.gif)
![Screenshot 2020-11-29 112327](https://user-images.githubusercontent.com/50356015/100534646-3e9d0500-3237-11eb-82ea-4ec45f5ed617.gif)
![Screenshot 2020-11-29 112709](https://user-images.githubusercontent.com/50356015/100534647-3fce3200-3237-11eb-87e5-a1ea6b7dad80.gif)
![Screenshot 2020-11-29 114141](https://user-images.githubusercontent.com/50356015/100534714-ea465500-3237-11eb-8ac7-406b1b116877.gif)

**Comment by REJack** [comment]
> ![Screenshot 2020-11-29 113611](https://user-images.githubusercontent.com/50356015/100534643-3b097e00-3237-11eb-87b2-c2a568127b07.gif)

That can't be overwritten without a custom class, for this bootstrap has the `.custom-file-input` class.

> ![Screenshot 2020-11-29 112038](https://user-images.githubusercontent.com/50356015/100534644-3c3aab00-3237-11eb-85eb-dd6794c8ef3a.gif)

That I've fixed.

> ![Screenshot 2020-11-29 112230](https://user-images.githubusercontent.com/50356015/100534645-3d6bd800-3237-11eb-9968-435d66cda7df.gif)

The sidebar at all are not affected by dark-mode, that's why this is still the default sidebar-dark look.

> ![Screenshot 2020-11-29 112327](https://user-images.githubusercontent.com/50356015/100534646-3e9d0500-3237-11eb-82ea-4ec45f5ed617.gif)

That can't be overwritten without a custom class, for this bootstrap has the `.custom-checkbox`, `.custom-radio` & `.custom-select` classes.

> ![Screenshot 2020-11-29 112709](https://user-images.githubusercontent.com/50356015/100534647-3fce3200-3237-11eb-87e5-a1ea6b7dad80.gif)

That I've fixed.

> ![Screenshot 2020-11-29 114141](https://user-images.githubusercontent.com/50356015/100534714-ea465500-3237-11eb-8ac7-406b1b116877.gif)

the dark mode doesn't affect any default inputs, it only is point to bootstrap classes (e.g. `form-control` / `.btn`).
