### ISSUE TITLE
[BUG] html css in v3.1.0-rc

### ISSUE THREAD

**Issue by danny007in** [ColorlibHQ/AdminLTE#3189]
![Screenshot 2020-12-03 213919](https://user-images.githubusercontent.com/50356015/101055684-28cd6e00-35b0-11eb-9659-45195465e319.gif)
![Screenshot 2020-11-30 093722](https://user-images.githubusercontent.com/50356015/101055696-2cf98b80-35b0-11eb-8420-8623fe9df75b.gif)
![Screenshot 2020-12-03 204054](https://user-images.githubusercontent.com/50356015/101055721-32ef6c80-35b0-11eb-91a8-315c20b85e93.gif)
![Screenshot 2020-12-03 204912](https://user-images.githubusercontent.com/50356015/101055739-38e54d80-35b0-11eb-917c-c14a4a8fb5d6.gif)
![Screenshot 2020-12-03 210703](https://user-images.githubusercontent.com/50356015/101055763-400c5b80-35b0-11eb-8006-5782c83aa313.gif)

**Comment by REJack** [comment]
1. Image: Thats the browsers default color and it's impossible on some browsers to override.
2. Image: We don't use GitHubs Package Repos thats why we have no packages online there.
3. Image: I've fixed this in master branch.
4. Image: I've fixed this in master branch.
5. Image: This comes from that the custom select's have `border-0` class to hide the ugly white border around colored custom selects inside the demo.js. Otherwise it look like this:
![grafik](https://user-images.githubusercontent.com/1554582/101132805-e9327080-3607-11eb-8f8e-147c5eeb4582.png)
