### ISSUE TITLE
[BUG] change navbar example to latest

### ISSUE THREAD

**Issue by danny007in** [ColorlibHQ/AdminLTE#3359]
![firefox_AdugtsPsBE](https://user-images.githubusercontent.com/50356015/105723965-5ea62780-5f4d-11eb-8d75-98aa099fb7f3.png)

**Comment by REJack** [comment]
The navbars have no dark-mode since they are colored by diffent classes.

**Comment by danny007in** [comment]
Any how change it to latest navbar example

**Comment by REJack** [comment]
Which navbar example you mean?

This example is the same like the main-header navbar only in a card

**Comment by danny007in** [comment]
that is not in latest searchbar effect

**Comment by Elghamed** [comment]
He meant it should be something like this I guess.
![image](https://user-images.githubusercontent.com/41231884/106371555-6c551600-636e-11eb-8259-bd11cbe43fee.png)
and when it's clicked, it expands taking the whole size of the navbar like this
![image](https://user-images.githubusercontent.com/41231884/106371585-cd7ce980-636e-11eb-9126-4ded7160992b.png)

**Comment by REJack** [comment]
@danny007in I will change it 😄 but we need to improve the NavbarSearch Script, all trigger together 🤣 and there is a icon visibility bug since bootstrap v4.6.0.

![Bildschirmfoto 2021-02-02 um 07 56 55](https://user-images.githubusercontent.com/1554582/106563565-407f8f00-652c-11eb-8b86-a4794b3f2a61.png)

**Comment by REJack** [comment]
done 😄
