### ISSUE TITLE
are u using Laravel with the new version ?

### ISSUE THREAD

**Issue by muhanadali100** [ColorlibHQ/AdminLTE#3712]
are u using Laravel with the AdminLTE V4 ?

**Comment by danny007in** [comment]
actually adminlte is bootstrap theme

**Comment by REJack** [comment]
> are u using Laravel with the AdminLTE V4 ?

I'm sure that before AdminLTE v4 is released, [Laravel-AdminLTE](https://github.com/jeroennoten/Laravel-AdminLTE/) will come with compatible version too.

**Comment by muhanadali100** [comment]
> are u using Laravel with the AdminLTE V4 ?

no i don't mean that, but i see the edit in V4 so I thought it was Laravel 

I don't know how to use laravel and i don't have time to learn it

**Comment by REJack** [comment]
that's are two diffent point 😄 AdminLTE is only a Theme/Template; Laravel is a Framework based on PHP. AdminLTE will never come bundled with a Framework either for PHP or other languages, otherwise ppl would need to port it into a other language and that's harder than to implement it from HTML/JS Demos.
