### ISSUE TITLE
[QUESTION] IFrame plugin usage

### ISSUE THREAD

**Issue by taufardh** [ColorlibHQ/AdminLTE#3726]
AdminLTE iframe plugin is awesome... 
and then I have several question about it.
That feature literally use iframe, in demo iframe can load every page in AdminLTE which is good, but I hear many disadvantage or cons from using iframe, security problem for example. If I use it in my web project and make iframe plugins to load every page in my app is that safe? or will be a security breach for my application? I'll use php framework as backend, and do you have any suggestion for it? 
I hope I can use Iframe plugin safely for my project... 
Thank you

**Comment by uchoamaster** [comment]
how do you use this plugin? could you give me a hand? I'm trying to implement it in my project but I'm not able to load the pages for it...

**Comment by taufardh** [comment]
> how do you use this plugin? could you give me a hand? I'm trying to implement it in my project but I'm not able to load the pages for it...

just load iframe html in main view and then add link to sidebar to load another view

**Comment by REJack** [comment]
iframes doesn't add's security problems, that always depends on your application checks. also there is no alternative to iframes otherwise you append the extra html to your main page but then you have massive problems with the javascripts that's why iframes nearby the only solution for this like operation.

**Comment by REJack** [comment]
I close this issue due inactivity.
