### ISSUE TITLE
[BUG] No license file for jquery-knob plugin

### ISSUE THREAD

**Issue by hyandell** [ColorlibHQ/AdminLTE#4067]
**Describe the bug**
Looking at the jquery-knob plugin, I'm not seeing any licensing information. 

I think it's this project, available under MIT license, https://github.com/aterrien/jQuery-Knob

**To Reproduce**
See https://github.com/ColorlibHQ/AdminLTE/tree/master/plugins/jquery-knob 

**Expected behavior**
That https://github.com/aterrien/jQuery-Knob/blob/master/LICENSE would be present in the directory, or that there would be a short source header on the min.js file.

**Environment (please complete the following information):**
- AdminLTE Version: Latest GitHub on this date
- Operating System:  n/a
- Browser (Version): n/a

**Comment by REJack** [comment]
We not modify the added Plugins so we wont add the license to the plugins if the author doesn't add it.

**Comment by pombredanne** [comment]
@REJack my 2 cents... from what I can see upstream includes a license notice alright everywhere in the repo  https://github.com/aterrien/jQuery-Knob/ 
I am not sure that the fact only one file was cherry picked at https://github.com/aterrien/jQuery-Knob/blob/master/dist/jquery.knob.min.js means that this should not come with the license and credits otherwise present in the upstream codebase and package manifests. You do not have to modify the code.
